apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e1kvdoj71-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e1kvdoj71-go 
  name: e1kvdoj71-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: e1kvdoj71-go 
